# Generated by Django 5.2.2 on 2025-06-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='active_at',
            field=models.DateTimeField(null=True),
        ),
    ]
